services:
  web:
    build: .
    container_name: jobrecs-web
    ports:
    - "3000:3000"
    environment:
    - BACKEND_BASE_URL=http://localhost:8686
networks:
  public-network:
    external: true
    name: mse_net
